create table beneficiario (
      id bigint generated by default as identity,
      data_atualizacao timestamp(6) not null,
      data_inclusao timestamp(6) not null,
      data_nascimento date not null,
      nome varchar(100) not null,
      telefone varchar(11) not null,
      primary key (id)
);

create table documento (
       id bigint generated by default as identity,
       data_atualizacao timestamp(6) not null,
       data_inclusao timestamp(6) not null,
       descricao varchar(14) not null,
       tipo_documento varchar(4) not null check (tipo_documento in ('RG','CPF','CNPJ')),
       beneficiario_id bigint not null,
       primary key (id)
);

alter table if exists documento
    add constraint FK3639o3852yoa4fxsjd6kk5vub
    foreign key (beneficiario_id)
    references beneficiario;

create table users (
       id bigint generated by default as identity,
       login varchar(40) not null,
       password varchar(255) not null,
       role varchar(5) not null check (role in ('USER','ADMIN')),
       primary key (id)
);

/*INSERT INTO USERS(LOGIN, PASSWORD, ROLE) VALUES ('ekan', '12345', 'ADMIN');*/
INSERT INTO USERS(LOGIN, PASSWORD, ROLE) VALUES ('ekan', '$2a$10$u.Dn2iILuobr9DLj48Hw8eVapwZW8PNDY9Y5lTcmxixJyQHi678YW', 'ADMIN');
